# General site settings
author: phdenzel
author_name: Philipp Denzel
email: phdenzel@gmail.com

description: > # this means ignore newlines until "baseurl:"
  Astrophysicist // Hacker // Climber

github_username: phdenzel
twitter_username: phdenzel

# Header
menu:
- {name: about me, url: '#about-me'}
- {name: my work, url: '#my-work'}
- {name: lab, url: '#lab'}
- {name: teaching, url: '#teaching'}
- {name: contact, url: '#contact'}


# About me
about-me: >
  **Hi there!** I'm a computational astrophysicist and machine
  learning engineer working at the [Centre for Artificial
  Intelligence](https://www.zhaw.ch/en/engineering/institutes-centres/cai/)
  as a researcher in deep learning and AI.

  
  My interests are broad, and during my [academic
  career](/assets/files/cv.pdf) I dabbled in many research fields such
  as general relativity, cosmology, galactic dynamics, stellar
  formation, computational astrophysics, fluid dynamics, physical
  chemistry, molecular dynamics, and high-performance computing.

  
  Currently, I'm working on a project within the Swiss SKA consortium
  [SKACH](https://skach.org/) on generative deep learning methods for
  astrophysical radio observations from cosmological simulations (and
  vice versa).

  
  When not doing sciency stuff or "hacking away" on my laptop, I'm
  most likely to be found on a climbing wall in my favorite
  [bouldering](http://minimum.ch/) or [climbing](http://griffig.com/)
  gyms in Zurich, or downhill on my mountain bike.

  Gardening is another passion of mine. I'm particularly proud of my
  many chili plants which I try to grow every season.

  Although I am not very good at it, I occasionally play guitar and
  rarely piano.  However, what I'm very good at is drinking coffee,
  playing pool, and other things that encourage my recreational
  "idea-fueling" phases 😅.

science-quote: >
  **_Science isn't about WHY, it's about WHY NOT..._**

skills:
- {name: Programming, value: '10'}
- {name: Physics, value: '8'}
- {name: Teaching, value: '7'}
- {name: Learning, value: '7'}
- {name: Creativity, value: '9'}
- {name: Communication, value: '6'}
- {name: Web Design, value: '4'}
- {name: Organization, value: '5'}


# My work
projects:
- {name: 'Dark matter detection', folder: 'bubble', file: 'projects/bubble.html'}
- {name: 'Star formation', folder: 'sform', file: 'projects/sform.html'}
- {name: 'Gravitational lensing', folder: 'glens', file: 'projects/glens.html'}


# Teaching
classes:
  - {name: 'Scientific Computing ', semester: 'FS18', description: 'Using python to solve problems in maths and science', folder: 'scicomp', page: 'teaching/FS18-SciComp', link: 'https://mnf.openedx.uzh.ch/courses/course-v1:MNF+PHY124+FS2021/about'}
  - {name: 'Introduction to Astrophysics & Cosmology ', semester: 'HS17', description: 'Using simple ideas to solve the Universe', folder: 'astro', page: 'teaching/HS17-Astro', link: 'https://www.physik.uzh.ch/~psaha/magicenv/'}
  - {name: 'Computer Simulations ', semester: 'FS17', description: 'Experimenting right in the classroom', folder: 'spin', page: 'teaching/FS17-Spin', link: 'https://www.ics.uzh.ch/~stadel/doku.php?id=spin:start'}


# Contact
social:
  - {icon: 'linkedin', link: 'https://www.linkedin.com/in/philipp-denzel-7ab933142/'}
#  - {icon: 'docker', link: 'https://hub.docker.com/u/phdenzel/'}
  - {icon: 'github', link: 'https://github.com/phdenzel'}
  - {icon: 'twitter', link: 'http://twitter.com/phdenzel'}
  - {icon: 'youtube', link: 'https://www.youtube.com/channel/UCBwsuXteT4O76NO46X6K3nA'}
